### ISSUE TITLE
Linux version of mod2gbt

### ISSUE THREAD

**Issue by bashaus** [AntonioND/gbt-player#1]
Is it possible that you can include an executable version of mod2gbt for linux/unix/osx? It would make compiling much easier.

Love the work you've done on GBT player.

**Comment by AntonioND** [comment]
Well, I'm not sure that's a good idea... Even though it's a very simple program I'm not sure it would be 100% compatible with all distros. I don't know much about that things, to be honest.

What I think is a better idea is to add a .sh script to compile it. Well, script... A single command: 
gcc -o mod2gbt mod2gbt.c
