### ISSUE TITLE
Broken link from Readme

### ISSUE THREAD

**Issue by bbbbbr** [AntonioND/gbt-player#12]
Just a small issue, there is a broken link in the default README.rst:

This: http://www.skylyrac.net/gbt-player-usage.html
Should be: http://www.skylyrac.net/2015-04-08-gbt-player-usage.html

**Comment by AntonioND** [comment]
Thanks! Fixed in https://github.com/AntonioND/gbt-player/commit/08f018525e377323cb1d08c636a64a56eac4a6a4
