### ISSUE TITLE
`s3m2gbt` parse errors use exit calls

### ISSUE THREAD

**Issue by GValiente** [AntonioND/gbt-player#17]
Could you replace exit calls in `s3m2gbt` with exceptions or something else that doesn't abort the Python interpreter?

https://github.com/AntonioND/gbt-player/blob/78a61a68a8c541aa1445f9303e2839a3d16ee45c/gba/s3m2gbt/s3m2gbt.py#L55

**Comment by AntonioND** [comment]
I was thinking about error codes, but exceptions are probably better in this case.

**Comment by GValiente** [comment]
You could raise exceptions with both a message and an error code.

**Comment by AntonioND** [comment]
I'm not sure of what you mean, can you write an example? I almost never use exceptions...

**Comment by AntonioND** [comment]
https://github.com/AntonioND/gbt-player/commit/66a841bea799be3221f406121f090c229ebce536

I've made a few more changes. They don't have an error code, but now the exceptions that ``s3m2gbt`` can generate are custom exceptions.
