### ISSUE TITLE
`smt2gbt`: unresolved references to `pattern` and `step` variables

### ISSUE THREAD

**Issue by GValiente** [AntonioND/gbt-player#18]
`pattern` and `step` variables don't exist here: https://github.com/AntonioND/gbt-player/blob/1a922b80e609958aed34ade458ce6956df2b8fa1/gba/s3m2gbt/s3m2gbt.py#L306

**Comment by AntonioND** [comment]
This is now not a problem, I've refactored a lot the error handling of this script.

66a841bea799be3
