### ISSUE TITLE
Fix for noise channel 4 panning (hex is 44 instead of 88)

### ISSUE THREAD

**Issue by RichardULZ** [AntonioND/gbt-player#4]
Previously, would stop the noise channel when using a pan effect on ch4, tested and fixed with gbstudio.

https://github.com/AntonioND/gbt-player/blob/d3e57ac2742c7e7b651b7914d72bb52a84378420/rgbds_example/gbt_player_bank1.asm#L1309
https://github.com/AntonioND/gbt-player/blob/d3e57ac2742c7e7b651b7914d72bb52a84378420/legacy_gbdk/gbdk_example/gbt_player_bank1.s#L1328

Fix as 
```
gbt_ch4_pan$:
	and	a,#0x88
	ld	(gbt_pan+3),a
	ld	a,#1
	ret ; ret 1
```

**Comment by AntonioND** [comment]
Fixed in https://github.com/AntonioND/gbt-player/commit/001b78bcb3e46f94aa36626b1a2319f14c3767a6 and included in a new release: https://github.com/AntonioND/gbt-player/releases/tag/v3.0.7

Thanks.
